### PR TITLE
Simple emoji fix

### PR DESCRIPTION
**Pull request by phatmann**

### CODE REVIEW

**Comment by 3lvis** [comment]
@phatmann Thanks! Could you add a unit test, please?

**Comment by phatmann** [comment]
I added emoji test. I had to fix an issue where the tests would crash because the range length was incorrect. Also fixed a spelling error in the tests 🤓

**Comment by 3lvis** [comment]
@phatmann Thanks <3

**Comment by 3lvis** [comment]
Added `testEmoji` to `master` and it was already passing. I'm wondering what we could do to test this, having it tested will ensure that we don't break the fix in the future.

**Comment by 3lvis** [comment]
Added a demo project to try it out and saw the crash 👌 
simulator screen shot 20 apr 2017 10 43 57

**Pull request merged**
