### PR TITLE
Fix for emoji

### PR DESCRIPTION
**Pull request by gennick**

### CODE REVIEW

**Comment by gennick** [comment]
Could you please do some testing as it was very quick fix

**Comment by 3lvis** [comment]
Thanks!

**Comment by phatmann** [comment]
@3lvis This needs to be merged, as the current code causes a nasty crash.

Since we have an NSRange (and therefore a Foundation dependency) and not a Range object, the code can be vastly simplified:

```
    public func composedString(_ replacementString: String?, fullString: String?, inRange range: NSRange?) -> String {
        if let replacementString = replacementString, let range = range, let fullString = fullString as NSString? {
            return fullString.replacingCharacters(in: range, with: replacementString)
        }

        return fullString ?? ""
    }
```

**Comment by phatmann** [comment]
@3lvis Just created a PR with my simple fix: #21

**Comment by 3lvis** [comment]
We'll continue with the fix in https://github.com/3lvis/InputValidator/pull/21

**Pull request closed without merging**
